apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    control-plane: controller-manager
data:
  env: {{ include "chart.envFile" . | b64enc | quote }}
  values.yaml: {{ .Values.values | toYaml | b64enc | quote }}
