{{- if .Values.rbac.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  name: wordpress-job-invoker
rules:
- apiGroups:
    - "apps"
  resources:
  - deployments
  verbs:
  - get
- apiGroups:
    - ""
  resources:
  - pods
  verbs:
  - list
- apiGroups:
    - ""
  resources:
  - pods/exec
  verbs:
  - create
{{- end -}}
